version: "3.7"
services:
  
  recommender:
    image: taquanghung1705199/fhs_camera_ai:0.1
    volumes:
      - .:/FastMOT
      - ./data/:/FastMOT/src/data/
      - /tmp/.X11-unix:/tmp/.X11-unix

    environment:
      DISPLAY: $DISPLAY
      FLASK_ENV: development

    deploy:
      resources:
        limits:
          cpus: '1'
          memory: '1G'
    
    network_mode: "host"
    command: bash -c "tail -f /dev/null"
